### PR TITLE
Fix/windows support

### LINKED ISSUE #5: Tool does not recognize local branches on Windows
Hi @stefanwille,
maybe I got it wrong, but see the output of the tool below. Why didn't it see the local branches?
image

Tried both via Node.JS console and Git Bash.

### PR DESCRIPTION
**Pull request by KamilPacanek**
On Windows, regardless if using Git Bash (MINGW64) or Node.js specific console, return value of `child_process.execSync(...)` is truncated at space. Proposed solution is using something different from space in the `git for-each-ref --format` command. 

**Please verify compatibility with other OS you are using.** 

Resolves #5 

Worth noting, that due to usage of `enquirer` package, tool won't work on Git Bash. The reason behind it - probable because Git Bash is not an interactive/TTY shell ([MINGW64 is not supported @ enquirer](https://github.com/enquirer/enquirer/issues/106#issuecomment-1113269738)).

### CODE REVIEW

File: src/git-branch-delete.ts [hunk 1]
```diff
@@ -30,11 +30,11 @@ const isGitRepository = (): boolean => {
 
 const getGitBranches = (): GitBranch[] => {
   const cmd =
-    "git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(refname:short):::%(committerdate:relative):::%(committerdate:iso8601)'";
+    "git for-each-ref --sort=committerdate refs/heads/ --format=%(HEAD):%(refname:short):::%(committerdate:relative):::%(committerdate:iso8601)";
```
Comment (stefanwille) [inline src/git-branch-delete.ts]: Hi Kamil , thanks for your PR. 

I have tried your changes and I found that I have to put the ticks `'` back in. Otherwise the code breaks on MacOS. Are the ticks an issue on Windows?

Comment (KamilPacanek) [reply src/git-branch-delete.ts]: On Windows works either way, but in case format is enclosed with `'`, returns that tick `'` in output, so it needs to be calculated in later `filter` and `substring` functions.
Another way is to remove all `'` characters right after splitting by newlines. Branch name won't include `'` so it should not be conflicts there.

**Comment by stefanwille** [comment]
Thanks!
